### ISSUE TITLE
Missing image-to-image notebook links in main site

### ISSUE THREAD

**Issue by iarganda** [BiaPyX/BiaPyX.github.io#2]
The links (buttons) to the image-to-image translation notebooks are missing from the main site:
![Screenshot from 2024-11-26 11-26-17](https://github.com/user-attachments/assets/165ba217-e8c8-4482-a275-ef51236b4776)

**Comment by danifranco** [comment]
Added them in f3cc6aff05404aa40de3254e32f2bea08c3d0ca6 . However we need to find a way of setting there a horizontal scroll as all the cards have been moved and now there are three rows there...

**Comment by danifranco** [comment]
Fixed in bd8de3fad72f45426d93cf4678ca37efb62c1630!
